export type Data = {
  num: string;
  name: string;
  amount: string;
  year: string;
  brand: string;
  color: string;
  favorite: boolean;
  category: string;
  price: string;
  description: string;
};

export const data: Data[] = [
  {
    num: '1',
    name: 'ELEMENT PEANUTS ROY X',
    amount: '2',
    year: '2018',
    brand: 'element',
    color: 'green',
    favorite: false,
    category: 'decks',
    price: '41',
    description: 'Fucking Awesome ELEMENT PEANUTS ROY X Skateboard Deck',
  },
  {
    num: '2',
    name: 'ELEMENT TIMBER ENTANGL',
    amount: '6',
    year: '2020',
    brand: 'element',
    color: 'black',
    favorite: true,
    category: 'decks',
    price: '46',
    description: 'Fucking Awesome ELEMENT TIMBER ENTANGL Skateboard Deck',
  },
  {
    num: '3',
    name: 'ELEMENT TIMBER SKELETON',
    amount: '4',
    year: '2021',
    brand: 'element',
    color: 'black',
    favorite: true,
    category: 'decks',
    price: '54',
    description: 'Fucking Awesome ELEMENT TIMBER SKELETON Skateboard Deck',

  },
  {
    num: '4',
    name: 'ELEMENT TIMBER HIGH DR',
    amount: '10',
    year: '2022',
    brand: 'element',
    color: 'black',
    favorite: false,
    category: 'decks',
    price: '85',
    description: 'Fucking Awesome ELEMENT TIMBER HIGH DR Skateboard Deck',
  },
  {
    num: '5',
    name: 'ANTI-HERO EVAN GRIMPLE',
    amount: '7',
    year: '2022',
    brand: 'anti-hero',
    color: 'yellow',
    favorite: false,
    category: 'decks',
    price: '70',
    description: 'Fucking Awesome ANTI-HERO EVAN GRIMPLE Skateboard Deck',
  },
  {
    num: '6',
    name: 'ANTI-HERO CARDIEL BURR',
    amount: '2',
    year: '2017',
    brand: 'anti-hero',
    color: 'yellow',
    favorite: false,
    category: 'decks',
    price: '79',
    description: 'Fucking Awesome ANTI-HERO CARDIEL BURR Skateboard Deck',
  },
  {
    num: '7',
    name: 'ANTI-HERO TRUJILLO MOTEL18',
    amount: '15',
    year: '2022',
    brand: 'anti-hero',
    color: 'green',
    favorite: false,
    category: 'decks',
    price: '41',
    description: 'Fucking Awesome ANTI-HERO TRUJILLO MOTEL18 Skateboard Deck',
  },
  {
    num: '8',
    name: 'ANTI-HERO AH BRD PFANNER GUEST GRIMPLE',
    amount: '1',
    year: '2015',
    brand: 'anti-hero',
    color: 'green',
    favorite: false,
    category: 'decks',
    price: '',
    description: 'Fucking Awesome ANTI-HERO AH BRD PFANNER GUEST GRIMPLE Skateboard Deck',
  },
  {
    num: '9',
    name: 'ANTI-HERO PRICEPOINT WHEEL OF ANTIHERO',
    amount: '4',
    year: '2019',
    brand: 'anti-hero',
    color: 'black',
    favorite: false,
    category: 'decks',
    price: '66',
    description: 'Fucking Awesome ANTI-HERO PRICEPOINT WHEEL OF ANTIHERO Skateboard Deck',
  },
  {
    num: '10',
    name: 'ANTI-HERO BRD CLASSIC EAGLE',
    amount: '2',
    year: '2018',
    brand: 'anti-hero',
    color: 'black',
    favorite: true,
    category: 'decks',
    price: '57',
    description: 'Fucking Awesome ANTI-HERO BRD CLASSIC EAGLE Skateboard Deck',
  },
  {
    num: '11',
    name: 'TOY MACHINE NEW FISTS',
    amount: '3',
    year: '2019',
    brand: 'toy-machine',
    color: 'black',
    favorite: false,
    category: 'decks',
    price: '31',
    description: 'Fucking Awesome TOY MACHINE NEW FISTS Skateboard Deck',
  },

  {
    num: '12',
    name: 'TOY MACHINE CAT MONSTER',
    amount: '10',
    year: '2015',
    brand: 'toy-machine',
    color: 'black',
    favorite: false,
    category: 'decks',
    price: '58',
    description: 'Fucking Awesome TOY MACHINE CAT MONSTER Skateboard Deck',
  },
  {
    num: '13',
    name: 'TOY MACHINE VICE HELL MONSTER',
    amount: '2',
    year: '2020',
    brand: 'toy-machine',
    color: 'yellow',
    favorite: true,
    category: 'decks',
    price: '40',
    description: 'Fucking Awesome TOY MACHINE VICE HELL MONSTER Skateboard Deck',
  },
  {
    num: '14',
    name: 'TOY MACHINE NO SCOOTER',
    amount: '7',
    year: '2018',
    brand: 'toy-machine',
    color: 'black',
    favorite: false,
    category: 'decks',
    price: '32',
    description: 'Fucking Awesome TOY MACHINE NO SCOOTER Skateboard Deck',
  },
  {
    num: '15',
    name: 'TOY MACHINE MONSTER MEDIUM',
    amount: '3',
    year: '2021',
    brand: 'toy-machine',
    color: 'yellow',
    favorite: false,
    category: 'decks',
    price: '81',
    description: 'Fucking Awesome TOY MACHINE MONSTER MEDIUM Skateboard Deck',
  },
  {
    num: '16',
    name: 'ELEMENT TRAPPED WESTGATE',
    amount: '2',
    year: '2020',
    brand: 'element',
    color: 'green',
    favorite: true,
    category: 'decks',
    price: '67',
    description: 'Fucking Awesome ELEMENT TRAPPED WESTGATE Skateboard Deck',
  },
  {
    num: '17',
    name: 'ELEMENT TIMBER GARDEN S',
    amount: '4',
    year: '2021',
    brand: 'element',
    color: 'green',
    favorite: false,
    category: 'decks',
    price: '54',
    description: 'Fucking Awesome ELEMENT TIMBER GARDEN S Skateboard Deck',
  },

  {
    num: '18',
    name: 'ELEMENT SEAL',
    amount: '1',
    year: '2019',
    brand: 'element',
    color: 'black',
    favorite: false,
    category: 'decks',
    price: '75',
    description: 'Fucking Awesome ELEMENT SEAL Skateboard Deck',
  },
  {
    num: '19',
    name: 'ELEMENT GALAXY',
    amount: '2',
    year: '2022',
    brand: 'element',
    color: 'black',
    favorite: false,
    category: 'decks',
    price: '42',
    description: 'Fucking Awesome ELEMENT GALAXY Skateboard Deck',
  },
  {
    num: '20',
    name: 'ELEMENT STAR WARS YODA',
    amount: '5',
    year: '2022',
    brand: 'element',
    color: 'yellow',
    favorite: false,
    category: 'decks',
    price: '35',
    description: 'Fucking Awesome ELEMENT STAR WARS YODA Skateboard Deck',
  },
  {
    num: '21',
    name: 'ELEMENT SHADOW ETHAN',
    amount: '1',
    year: '2021',
    brand: 'element',
    color: 'black',
    favorite: false,
    category: 'decks',
    price: '36',
    description: 'Fucking Awesome ELEMENT SHADOW ETHAN Skateboard Deck',
  },
  {
    num: '22',
    name: 'ELEMENT SPECTRUM CRUISER',
    amount: '10',
    year: '2022',
    brand: 'element',
    color: 'green',
    favorite: false,
    category: 'wheels',
    price: '10',
    description: 'Maximize your speed with ELEMENT SPECTRUM CRUISER skateboard wheels. This square lip designed wheel is built to optimize lock-ins and maximize stability on stalls and grinds. These wheels also feature a 99a durometer construction for grip on vert and predictable power slides when you want, with no flatspots, guaranteed',
  },
  {
    num: '23',
    name: 'TOY MACHINE BANDANA CRUISER SHAPE',
    amount: '10',
    year: '2020',
    brand: 'toy-machine',
    color: 'yellow',
    favorite: false,
    category: 'wheels',
    price: '10',
    description: 'Maximize your speed with TOY MACHINE BANDANA CRUISER SHAPE skateboard wheels. This square lip designed wheel is built to optimize lock-ins and maximize stability on stalls and grinds. These wheels also feature a 99a durometer construction for grip on vert and predictable power slides when you want, with no flatspots, guaranteed',
  },
  {
    num: '24',
    name: 'TENSOR ALUM TRIPPY CHARACTER ROGERS',
    amount: '8',
    year: '2021',
    brand: 'anti-hero',
    color: 'yellow',
    favorite: false,
    category: 'trucks',
    price: '58',
    description: 'All-new proprietary process strength at a molecular level the strongest cast truck ever made by Ace',
  },
  {
    num: '25',
    name: 'TENSOR ALUM CAMO',
    amount: '4',
    year: '2022',
    brand: 'element',
    color: 'black',
    favorite: false,
    category: 'trucks',
    price: '75',
    description: 'All-new proprietary process strength at a molecular level the strongest cast truck ever made by Ace',
  },

  {
    num: '26',
    name: 'ANON ECHO',
    amount: '1',
    year: '2022',
    brand: 'element',
    color: 'black',
    favorite: false,
    category: 'helmets',
    price: '107',
    description: 'MIPs technology: Motion Impact Protection system uses a internal low friction layer that allows the helmet to rotate. This adds protection for your brain during rotational impact',
  },


  {
    num: '27',
    name: 'ANON RODAN',
    amount: '2',
    year: '2022',
    brand: 'element',
    color: 'yellow',
    favorite: false,
    category: 'helmets',
    price: '92',
    description: 'MIPs technology: Motion Impact Protection system uses a internal low friction layer that allows the helmet to rotate. This adds protection for your brain during rotational impact',
  },
];